# Dependencies
kramdown:
  syntax_highlighter_opts:
    disable : true

# Permalinks
permalink: /posts/:title/
timezone: America/Sao_Paulo

exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - README.md
  - LICENSE.md
  - .sass-cache
  - .travis.yml
  - .ruby-version
  - .gitignore

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

sass:
  sass_dir: _scss
  style: compressed

paginate: 5

# Custom vars
show_related_posts: true
animated: true


# please change ALL items bellow if you are forking my repo!
# you may also want to edit about.md and delete all posts and images.

title: Carlos Alexandro Becker
description: 'Software development and related stuff, by Carlos A. Becker'
baseurl:     ''
google_analytics: UA-50435491-1
disqus_shortname: caarlos0blog

author:
  name: 'Ankur Kumar'
  email: ankur5126@icloud.com
  github: leakyrelu
  twitter: leakyrelu
  wakatime:
    username: 
    charts:
      - 613f0a05-b962-4524-b2b5-4a28b1cd8560
      - 8c92453c-7664-4810-9a33-2d2238c0d7ed
      - bec85d3b-488d-45e6-95d1-7e74b9e87156
