source 'https://rubygems.org'

gem 'github-pages', '~> 96'
gem 'jekyll-seo-tag'
gem 'jemoji'
gem 'jekyll-mentions'
gem 'jekyll-redirect-from'
gem 'jekyll-paginate'
gem 'html-proofer'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
